services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: ia_postgres
    environment:
      POSTGRES_DB: ia_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  vllm:
    image: vllm/vllm-openai:latest
    container_name: ia_vllm
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    command: >
      --model Qwen/Qwen2.5-7B-Instruct-AWQ
      --quantization awq
      --max-model-len 2048
      --gpu-memory-utilization 0.8
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"